# Generated by Django 5.2.8 on 2025-11-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='Welcome to my personal blog', max_length=300)),
                ('name', models.CharField(default='Kishorelin', max_length=100)),
                ('bio', models.TextField(help_text='Main bio/description text')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('topics', models.TextField(blank=True, help_text='List of topics you write about (one per line)')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
