# Generated by Django 5.2.8 on 2025-11-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_aboutpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='bio',
            field=models.TextField(blank=True, default="This is my personal blog where I share my thoughts, experiences, projects, and knowledge on various topics that interest me.\n\nI'm passionate about technology, programming, and continuous learning. Through this blog, I aim to document my journey, share what I've learned, and connect with like-minded individuals.", help_text='Main bio/description text'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='email',
            field=models.EmailField(blank=True, help_text='Your contact email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='github_url',
            field=models.URLField(blank=True, help_text='Your GitHub profile URL', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Your LinkedIn profile URL', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='topics',
            field=models.TextField(blank=True, default='Web Development\nSoftware Engineering\nTechnology Trends\nPersonal Projects\nLearning Experiences', help_text='List of topics you write about (one per line)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Your Twitter/X profile URL', null=True),
        ),
    ]
