# Generated by Django 5.2.8 on 2025-11-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_alter_aboutpage_bio_alter_aboutpage_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Get in Touch', max_length=200)),
                ('subtitle', models.TextField(blank=True, default="I'd love to hear from you. Send me a message and I'll respond as soon as possible.", max_length=500)),
                ('email_label', models.CharField(blank=True, default='Email', max_length=100)),
                ('email_value', models.EmailField(blank=True, max_length=254, null=True)),
                ('github_label', models.CharField(blank=True, default='GitHub', max_length=100)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('github_value', models.CharField(blank=True, help_text='Display text for GitHub (e.g., github.com/username)', max_length=200, null=True)),
                ('linkedin_label', models.CharField(blank=True, default='LinkedIn', max_length=100)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('linkedin_value', models.CharField(blank=True, help_text='Display text for LinkedIn (e.g., linkedin.com/in/username)', max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
    ]
